language: scala

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.sbt/launchers

jdk:
  - oraclejdk8
scala:
  - 2.11.8
after_success:
  - bash <(curl -s https://codecov.io/bash)
sudo: false
script:
  - pushd sparkproject
  - sbt "set test in assembly := {}" clean compile test scalastyle
  - popd
before_cache:
  # Problem with class files being annoying
  - rm -rf sparkproject/target
