apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: pr-processor
    app: pr-processor
  name: pr-processor
  namespace: nova
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: pr-processor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: pr-processor
    spec:
      containers:
        - image: krisnova/pull-request-processor
          imagePullPolicy: Always
          name: pr-processor
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
            - containerPort: 80
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: pr-processor
  name: pr-processor
  namespace: nova
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    run: pr-processor
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fabulousaf
  namespace: nova
spec:
  rules:
    - host: fabulous.af
      http:
        paths:
          - path: /webhook
            backend:
              serviceName: pr-processor
              servicePort: 80
          - path: /auth
            backend:
              serviceName: pr-processor
              servicePort: 80